In [19]:
import pandas as pd

In [20]:
# test
df = pd.read_pickle("data.pkl")  
df

,open,close,high,low,volume,change,amplitude,Variance20,VR,BIAS5,MAC5,beta,residual_volatility
2015-01-05,10.16,10.18,10.35,9.92,450000439.0,-0.001965,0.043347,0.436818,1.762475,3.512559,0.966066,0.883844,-0.516154
2015-01-06,10.08,10.03,10.42,9.88,340818825.0,0.004985,0.054656,0.427168,1.937771,1.050379,0.989605,0.867071,-0.565309
2015-01-07,9.89,9.84,10.06,9.73,267460942.0,0.005081,0.033916,0.407180,1.664330,-1.583929,1.016094,0.877312,-0.599752
2015-01-08,9.85,9.51,9.90,9.47,221459917.0,0.035752,0.045407,0.285303,1.858286,-4.201517,1.043858,0.931441,-0.606060
2015-01-09,9.47,9.59,10.09,9.35,394634239.0,-0.012513,0.079144,0.273035,1.815913,-2.474956,1.025378,0.905770,-0.593756
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-05-26,14.41,14.19,14.43,14.07,101131756.0,0.015504,0.025586,0.116340,0.723723,-2.581354,1.026498,-0.251366,-0.229652
2022-05-27,14.29,14.18,14.35,14.11,72306674.0,0.007757,0.017009,0.115850,0.631008,-1.514099,1.015374,-0.246911,-0.298685
2022-05-30,14.26,14.08,14.28,14.04,89690123.0,0.012784,0.017094,0.058918,0.622305,-1.179113,1.011932,-0.279559,-0.308887
2022-05-31,14.07,14.16,14.18,14.00,93886855.0,-0.006356,0.012857,0.060092,0.623603,-0.281690,1.002825,-0.298671,-0.293788
2022-06-01,14.14,14.08,14.14,14.00,84529898.0,0.004261,0.010000,0.056487,0.663699,-0.410242,1.004119,-0.304642,-0.286350

In [21]:
# test nan
df.isnull().sum().sum()

0

In [24]:
# generate y1 and y2
df_add_y = df.copy()
df_add_y['y_close_f1'] = df_add_y['close'].shift(-1)
df_add_y['y_change_f1'] = df_add_y['change'].shift(-1)
# delete the last row
df_add_y = df_add_y.iloc[:-1,:]

In [25]:
# show the result
# from 2015.1.5 --- 2022.5.31 factors 13
df_add_y

,open,close,high,low,volume,change,amplitude,Variance20,VR,BIAS5,MAC5,beta,residual_volatility,y_close_f1,y_change_f1
2015-01-05,10.16,10.18,10.35,9.92,450000439.0,-0.001965,0.043347,0.436818,1.762475,3.512559,0.966066,0.883844,-0.516154,10.03,0.004985
2015-01-06,10.08,10.03,10.42,9.88,340818825.0,0.004985,0.054656,0.427168,1.937771,1.050379,0.989605,0.867071,-0.565309,9.84,0.005081
2015-01-07,9.89,9.84,10.06,9.73,267460942.0,0.005081,0.033916,0.407180,1.664330,-1.583929,1.016094,0.877312,-0.599752,9.51,0.035752
2015-01-08,9.85,9.51,9.90,9.47,221459917.0,0.035752,0.045407,0.285303,1.858286,-4.201517,1.043858,0.931441,-0.606060,9.59,-0.012513
2015-01-09,9.47,9.59,10.09,9.35,394634239.0,-0.012513,0.079144,0.273035,1.815913,-2.474956,1.025378,0.905770,-0.593756,9.39,0.006390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-05-25,14.43,14.39,14.49,14.30,60322826.0,0.002780,0.013287,0.182685,0.734732,-1.788152,1.018207,-0.231336,-0.244978,14.19,0.015504
2022-05-26,14.41,14.19,14.43,14.07,101131756.0,0.015504,0.025586,0.116340,0.723723,-2.581354,1.026498,-0.251366,-0.229652,14.18,0.007757
2022-05-27,14.29,14.18,14.35,14.11,72306674.0,0.007757,0.017009,0.115850,0.631008,-1.514099,1.015374,-0.246911,-0.298685,14.08,0.012784
2022-05-30,14.26,14.08,14.28,14.04,89690123.0,0.012784,0.017094,0.058918,0.622305,-1.179113,1.011932,-0.279559,-0.308887,14.16,-0.006356
2022-05-31,14.07,14.16,14.18,14.00,93886855.0,-0.006356,0.012857,0.060092,0.623603,-0.281690,1.002825,-0.298671,-0.293788,14.08,0.004261

In [26]:
# save
df_add_y.to_pickle("data_include_y.pkl")

In [27]:
# test
unpickled_df = pd.read_pickle("data_include_y.pkl")  
unpickled_df

,open,close,high,low,volume,change,amplitude,Variance20,VR,BIAS5,MAC5,beta,residual_volatility,y_close_f1,y_change_f1
2015-01-05,10.16,10.18,10.35,9.92,450000439.0,-0.001965,0.043347,0.436818,1.762475,3.512559,0.966066,0.883844,-0.516154,10.03,0.004985
2015-01-06,10.08,10.03,10.42,9.88,340818825.0,0.004985,0.054656,0.427168,1.937771,1.050379,0.989605,0.867071,-0.565309,9.84,0.005081
2015-01-07,9.89,9.84,10.06,9.73,267460942.0,0.005081,0.033916,0.407180,1.664330,-1.583929,1.016094,0.877312,-0.599752,9.51,0.035752
2015-01-08,9.85,9.51,9.90,9.47,221459917.0,0.035752,0.045407,0.285303,1.858286,-4.201517,1.043858,0.931441,-0.606060,9.59,-0.012513
2015-01-09,9.47,9.59,10.09,9.35,394634239.0,-0.012513,0.079144,0.273035,1.815913,-2.474956,1.025378,0.905770,-0.593756,9.39,0.006390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-05-25,14.43,14.39,14.49,14.30,60322826.0,0.002780,0.013287,0.182685,0.734732,-1.788152,1.018207,-0.231336,-0.244978,14.19,0.015504
2022-05-26,14.41,14.19,14.43,14.07,101131756.0,0.015504,0.025586,0.116340,0.723723,-2.581354,1.026498,-0.251366,-0.229652,14.18,0.007757
2022-05-27,14.29,14.18,14.35,14.11,72306674.0,0.007757,0.017009,0.115850,0.631008,-1.514099,1.015374,-0.246911,-0.298685,14.08,0.012784
2022-05-30,14.26,14.08,14.28,14.04,89690123.0,0.012784,0.017094,0.058918,0.622305,-1.179113,1.011932,-0.279559,-0.308887,14.16,-0.006356
2022-05-31,14.07,14.16,14.18,14.00,93886855.0,-0.006356,0.012857,0.060092,0.623603,-0.281690,1.002825,-0.298671,-0.293788,14.08,0.004261